### ISSUE TITLE
Add a django table for geo-location

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/webapp#1]
Since the server gets the ip of the sender, put it in a table with the (partial) results of http://ipinfo.io/. This should check if the ip is already known and fill in the information if it isn't. Information is `ip` (as the primary index), `city`, `region`, `country`, and  `loc`.

**Comment by peterfpeterson** [comment]
For giggles, try http://ipinfo.io/130.246.132.177

**Comment by micah-raney** [comment]
On the geolocation branch, trying to POST through the web interface (not JSON) on Usage or Feature
results in an error similar to this one:
https://github.com/encode/django-rest-framework/issues/2774

Commenting out their create() functions makes the error go away. However, this issue isn't present in
master, even with the same PIP packages. Something about the geolocation branch is breaking it.

**Comment by micah-raney** [comment]
Putting in faux data for post_data instead of json.loads(request.body) made the error go away, but failed to redirect after creating a resource. Is this expected? 

Will anyone even use the creation form? If not, could we get rid of it?

**Comment by micah-raney** [comment]
The error doesn't occur on the new Location viewset. It only occurs in feature and usage.

**Comment by micah-raney** [comment]
Discovered that the error is present in my version of master.
