### ISSUE TITLE
Mouseover bug for reports front page

### ISSUE THREAD

**Issue by micah-raney** [mantidproject/webapp#11]
When mousing over the graph on the front page, it's supposed to give you dates and data corresponding to the point your mouse hovers over. However, you only get a mouseover on the values in the initial graph. Today (June 9 2017), I can only mouseover values as far back as May 10. Even if I change the start date to May 9 or before, I can only get mouseover feedback on dates May 10 and after.

**Comment by peterfpeterson** [comment]
Since that plot is no longer supported, this issue is no longer valid.
