### ISSUE TITLE
Static assets cannot be located

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/webapp#8]
reports.mantidproject.org is no longer able to find any static assets. See below for the error message from the Chrome console:

![reports-static-error](https://user-images.githubusercontent.com/733773/26873661-808b6088-4b72-11e7-8585-25f2dbd75bda.png)

Most notable is that the `d3` graph is missing.

I see something similar if I click the `admin` link where the page has not styling.

**Comment by peterfpeterson** [comment]
I `ssh` into the server and ran `.../wsgi/openshift/manage.py collectstatic` which fixed the issue.
